---
- name: Check if S3 bucket exists
  command: bash -c "aws s3 ls | grep {{ s3_bucket_name }}"
  ignore_errors: True
  register: bucket_exists
  tags:
    - create_s3

- name: Create an S3 bucket
  s3: 
    bucket: "{{ s3_bucket_name }}"
    mode: create
    permission: private
    region: "{{ region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  when: bucket_exists|failed
  tags:
    - create_s3

- name: Encrypt the S3 bucket with a bucket policy
  s3_bucket:
    name: "{{ s3_bucket_name }}"
    policy: "{{ s3_bucket_policy }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"

- name: Run cron job to sync local automysqlbackups to S3 and delete local backups to free space
  cron:
    name: "Sync to S3"
    minute: "{{ s3_min }}"
    hour: "{{ s3_hour }}"
    day: "{{ s3_day }}"
    month: "{{ s3_month }}"
    weekday: "{{ s3_weekday }}"
    job: "/usr/local/bin/aws s3 sync /var/lib/automysqlbackup/daily s3://{{ s3_bucket_name }} --sse AES256 && rm -rf /var/lib/automysqlbackup/daily/*"
    state: present
  tags:
    - remote_backup
